name: VirtualRadar.CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '5.x'

      - name: Restore packages
        run:  nuget restore VirtualRadar.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: '[16.0.0.0,16.65535.65535.65535]'

      - name: Build Release x86
        run:  msbuild VirtualRadar.sln -property:Configuration=Release,Platform=x86 -nowarn:1570,1572,1573,1574,1584,1587,1591,1711

      - name: Build Release x64
        run:  msbuild VirtualRadar.sln -property:Configuration=Release,Platform=x64 -nowarn:1570,1572,1573,1574,1584,1587,1591,1711

      - name: Build x86 Installer
        run:  iscc /Q Installers\InnoSetup\VirtualRadar-x86.iss
