name: Test Checksums

on: push

jobs:
  test:
    steps:
      - uses: actions/checkout@v2

      - name:   Create checksum file
        run:    sha256sum LICENSE.txt > checksums-sha256.txt
        shell:  bash

      - name:   Convert line-endings
        run:    unix2dos checksums-sha256.txt
        shell:  bash
